infrastructure: ^3.3
php_settings:
  version: 7.4
  cli:
    memory_limit: "1024M"
crons:
  queuedjobs_task:
    time: '* * * * *'
    sake_once: 'dev/tasks/ProcessJobQueueTask'
    vhost: 'mysite'
shared_dirs:
  mysite:
    "addon-downloads": {}
url_rules:
  mysite:
    - '^/addon-downloads/': 'deny'
